version: '3.8'
services:
  web:
    build: .
    depends_on:
      - mysqldb
    environment:
      DB_HOST: mysqldb
      DB_USER: buddies_user7
      DB_PASSWORD: Buddies@5000
      DB_NAME: mydb
      SECRET_KEY: VerySecure@71password
    expose:
      - "8000"

  mysqldb:
    image: mysql:8.0
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Buddies@7000
      MYSQL_DATABASE: mydb
      MYSQL_USER: buddies_user7
      MYSQL_PASSWORD: Buddies@5000

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    depends_on:
      - db
    ports:
      - "9000:9000"   # Web UI
      - "9092:9092"   # Internal communication
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

  db:
    image: postgres:latest
    container_name: sonarqube_db
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
    volumes:
      - postgresql:/var/lib/postgresql

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  mysql-data:
