name: Deploy to EC2

permissions:
  contents: read

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: SSH into EC2 instance, create env file and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/student23/ICT2216_Group23
            echo "DB_HOST=${{ secrets.DB_HOST }}" > .env
            echo "DB_USER=${{ secrets.DB_USER }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
            echo "SQL_ROOT_PASSWORD=${{ secrets.SQL_ROOT_PASSWORD }}" >> .env
            echo "FLASK_SECRET_KEY=${{ secrets.FLASK_SECRET_KEY }}" >> .env
            echo "CERTBOT_EMAIL=${{ secrets.CERTBOT_EMAIL }}" >> .env
            echo "EMAILVERIFICATION_API_KEY=${{ secrets.EMAILVERIFICATION_API_KEY }}" >> .env
            git pull
            sudo docker compose down
            sudo docker compose up -d --build

            sleep 30

            sudo docker compose exec mysqldb mysql -uroot -p${{ secrets.SQL_ROOT_PASSWORD }} -e \
              "REVOKE ALL PRIVILEGES, GRANT OPTION FROM '${{ secrets.DB_USER }}'@'%'; \
              GRANT SELECT, INSERT, UPDATE, DELETE ON \`${{ secrets.DB_NAME }}\`.* TO '${{ secrets.DB_USER }}'@'%'; \
              FLUSH PRIVILEGES;"
