name: Pylint check

permissions:
  contents: read
  
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pylint-typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pylint

      - name: Lint with pylint (only unused imports)
        run: find . -type f -name "*.py" ! -path "./venv/*" -print0 | xargs -0 pylint --disable=all --enable=W0611



