name: Run Unit Tests

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Wait for DB
        run: |
          sleep 5

      - name: Run Unit Tests
        run: | 
          python -m tests.unit.unit_test