name: Validate

on:
  push:
    branches:
      - main
  pull_request:

# checks whether your Nginx container is correctly configured to reverse proxy requests  
# to the Flask application running in a separate Docker container

jobs:
  test-flask-nginx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Flask Docker image
        run: docker build -t flask-app .

      - name: Create Docker network
        run: docker network create mytestnet

      - name: Start Flask container (Gunicorn)
        run: docker run -d --name web --network mytestnet flask-app

      - name: Start Nginx container
        run: |
          docker run -d --name nginx-test --network mytestnet -p 8080:80 \
            -v ${{ github.workspace }}/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro \
            nginx:latest

      - name: Wait for services to start
        run: sleep 5

      - name: List running containers
        run: docker ps -a

      - name: Nginx logs
        run: docker logs nginx-test || true

      - name: Check port mapping
        run: docker port nginx-test

      - name: Test Flask route via Nginx
        run: |
          curl -s -o response.html http://localhost:8080/
          grep "Login Page" response.html
    
      - name: Stop containers
        run: |
          docker stop nginx-test
          docker stop web
